apiVersion: apps/v1
kind: Deployment
metadata:
  name: delta-neutral-deployment
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delta-neutral
  template:
    metadata:
      labels:
        app: delta-neutral
    spec:
      containers:
      - name: delta-neutral-container
        image: ljheal/delta-neutral:latest
        ports:
        - containerPort: 8000
