apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delta-neutral-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: api.delta-neutral.louisheal.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: delta-neutral-service
            port:
              number: 80

  tls:
  - hosts:
    - api.delta-neutral.louisheal.com
    secretName: delta-neutral-tls 
